export enum PreInscriptionStatus {
  NEW = 'NEW',
  ASSIGNED_TO_COMMERCIAL = 'ASSIGNED_TO_COMMERCIAL',
  COMMERCIAL_REVIEW = 'COMMERCIAL_REVIEW',
  SENT_TO_ADMIN = 'SENT_TO_ADMIN',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CONVERTED = 'CONVERTED',
}

