CREATE TABLE IF NOT EXISTS `auditor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `class_student_id` INT NULL,
  `required_doc_id` INT NULL,
  `title` VARCHAR(255) NOT NULL,
  `is_required_snapshot` TINYINT(1) NOT NULL,
  `program_id` INT NOT NULL,
  `specialization_id` INT NOT NULL,
  `level_id` INT NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `file_path` VARCHAR(512) NULL,
  `verified_by_user_id` INT NULL,
  `verified_at` DATETIME NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_auditor_student_template` (`student_id`, `required_doc_id`),
  CONSTRAINT `FK_auditor_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_auditor_student` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_auditor_class_student` FOREIGN KEY (`class_student_id`) REFERENCES `class_students` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_auditor_required_doc` FOREIGN KEY (`required_doc_id`) REFERENCES `required_docs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_auditor_verified_by` FOREIGN KEY (`verified_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
